spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miboot?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver