server:
  port: 8989
spring:
  application:
    name: hebiyusheng
  datasource:
    url: jdbc:mysql://localhost:3306/miboot?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    remote:
      restart:
        enabled: true
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.zkr.hebiyusheng.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl