server:
  port: 8089
spring:
  application:
    name: springboot-redis
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.10.163:3306/miboot?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: org.springframework.jdbc.datasource.WebSphereDataSourceAdapter
# redis
  redis:
    host: 121.5.10.163
    port: 6379
    password: hebiyusheng
    # 默认使用1号数据库磁盘
    database: 1
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        min-idle: 0
        max-idle: 8
# 打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
